function env(key: string, fallback: string): string {
  return process.env[key] ?? fallback;
}

export const APP_NAME = env('EXPO_PUBLIC_APP_NAME', 'PV_Mind Cockpit');
export const MOBILE_APP_NAME = 'PV_Mind';
export const PARENT_BRAND = env('EXPO_PUBLIC_PARENT_BRAND', 'GridMind EPC');
export const PUBLIC_URL = env('EXPO_PUBLIC_PUBLIC_URL', 'https://pvmind.ai');
export const APP_URL = env('EXPO_PUBLIC_APP_URL', 'https://app.pvmind.ai');
export const API_URL = env('EXPO_PUBLIC_API_URL', 'https://api.pvmind.ai');
export const SUPPORT_EMAIL = env('EXPO_PUBLIC_SUPPORT_EMAIL', 'support@pvmind.ai');
export const NO_REPLY_EMAIL = env('EXPO_PUBLIC_NO_REPLY_EMAIL', 'no-reply@pvmind.ai');
export const ADMIN_EMAIL = 'admin@pvmind.ai';
export const REPORT_BRAND_NAME = env(
  'EXPO_PUBLIC_REPORT_BRAND_NAME',
  'PV_Mind Cockpit by GridMind EPC'
);

export const APP_SUBTITLE =
  'A GridMind EPC Solar PV + BESS Design, Simulation, Yield, SCADA, and Reporting Platform';
export const APP_DESCRIPTION =
  'PV_Mind Cockpit helps engineers and developers create PV and PV+BESS projects, validate stringing, estimate yield, calculate CAPEX, generate BOM/BOQ, preview SLDs, monitor SCADA telemetry, and export project reports.';

export const DOMAIN = 'pvmind.ai';
export const DEEP_LINK_SCHEME = 'pvmind';
export const AUTH_CALLBACK_PATH = 'auth/callback';

export const MOBILE_AUTH_CALLBACK_URI = `${DEEP_LINK_SCHEME}://${AUTH_CALLBACK_PATH}`;
export const WEB_AUTH_CALLBACK_URL = `${APP_URL}/${AUTH_CALLBACK_PATH}`;

/** Register these redirect URLs in the Supabase dashboard. */
export const SUPABASE_AUTH_REDIRECT_URLS = [
  PUBLIC_URL,
  'https://www.pvmind.ai',
  APP_URL,
  WEB_AUTH_CALLBACK_URL,
  MOBILE_AUTH_CALLBACK_URI,
] as const;

export const REPORT_HEADER = {
  title: 'PV_Mind Cockpit',
  subtitle: 'A GridMind EPC Platform',
  domain: DOMAIN,
} as const;

export const REPORT_FOOTER = `Generated by ${REPORT_HEADER.title} — ${REPORT_HEADER.domain}`;
export const EMAIL_FOOTER = `${REPORT_BRAND_NAME}\n${PUBLIC_URL}`;

export const BUNDLE_IDENTIFIER = 'ai.pvmind.app';
export const MACOS_BUNDLE_IDENTIFIER = 'ai.pvmind.desktop';
export const STORAGE_NAMESPACE = 'pvmind';

export function storageKey(suffix: string): string {
  return `${STORAGE_NAMESPACE}.${suffix}`;
}
